# Generated by Django 4.2.5 on 2023-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuboid_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
